export const mockData = [
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "b1d36ae48dd9d63a",
    id: "2ecd12259f211e78",
    name: "loadcomponents.loadcomponents",
    timestamp: 1725004322053000,
    duration: 57447,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "LoadComponents.loadComponents",
      "next.span_type": "LoadComponents.loadComponents",
      "node.env": "development",
      "operation.name": "next_js.LoadComponents.loadComponents",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "e292cb88211f8a7c",
    id: "b1d36ae48dd9d63a",
    name: "resolve page components",
    timestamp: 1725004322053000,
    duration: 60277,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.route": "/",
      "next.span_name": "resolve page components",
      "next.span_type": "NextNodeServer.findPageComponents",
      "node.env": "development",
      "operation.name": "next_js.NextNodeServer.findPageComponents",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "a09df23115da267e",
    id: "49fefb2655261dee",
    name: "resolve segment modules",
    timestamp: 1725004322132000,
    duration: 177,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.segment": "__PAGE__",
      "next.span_name": "resolve segment modules",
      "next.span_type": "NextNodeServer.getLayoutOrPageModule",
      "node.env": "development",
      "operation.name": "next_js.NextNodeServer.getLayoutOrPageModule",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "a09df23115da267e",
    name: "build component tree",
    timestamp: 1725004322128000,
    duration: 5558,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "build component tree",
      "next.span_type": "NextNodeServer.createComponentTree",
      "node.env": "development",
      "operation.name": "next_js.NextNodeServer.createComponentTree",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "a09df23115da267e",
    id: "31735508ebc0279e",
    name: "resolve segment modules",
    timestamp: 1725004322129000,
    duration: 534,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.segment": "",
      "next.span_name": "resolve segment modules",
      "next.span_type": "NextNodeServer.getLayoutOrPageModule",
      "node.env": "development",
      "operation.name": "next_js.NextNodeServer.getLayoutOrPageModule",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "ec19b3e13ebe250f",
    kind: "CLIENT",
    name: "fetching hello this is a test to see what happens get https://pokeapi.co/api/v2/pokemon/ditto",
    timestamp: 1725004322152000,
    duration: 166679,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      cached: "false",
      "http.method": "GET",
      "http.url": "https://pokeapi.co/api/v2/pokemon/ditto",
      "net.peer.name": "pokeapi.co",
      "next.span_name":
        "fetching hello this is a test to see what happens GET https://pokeapi.co/api/v2/pokemon/ditto",
      "next.span_type": "AppRender.fetch.hello.this.is.a.test",
      "node.env": "development",
      "operation.name": "next_js.AppRender.fetch.hello.this.is.a.test",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "991fa9b914d9a73d",
    kind: "CLIENT",
    name: "fetching hello this is a test to see what happens get https://pokeapi.co/api/v2/pokemon/ditto",
    timestamp: 1725004322154000,
    duration: 168827,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      cached: "true",
      "http.method": "GET",
      "http.url": "https://pokeapi.co/api/v2/pokemon/ditto",
      "net.peer.name": "pokeapi.co",
      "next.span_name":
        "fetching hello this is a test to see what happens GET https://pokeapi.co/api/v2/pokemon/ditto",
      "next.span_type": "AppRender.fetch.hello.this.is.a.test",
      "node.env": "development",
      "operation.name": "next_js.AppRender.fetch.hello.this.is.a.test",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "cffe7084f1924055",
    kind: "CLIENT",
    name: "fetching hello this is a test to see what happens get https://pokeapi.co/api/v2/pokemon/ditto",
    timestamp: 1725004322154000,
    duration: 169505,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      cached: "true",
      "http.method": "GET",
      "http.url": "https://pokeapi.co/api/v2/pokemon/ditto",
      "net.peer.name": "pokeapi.co",
      "next.span_name":
        "fetching hello this is a test to see what happens GET https://pokeapi.co/api/v2/pokemon/ditto",
      "next.span_type": "AppRender.fetch.hello.this.is.a.test",
      "node.env": "development",
      "operation.name": "next_js.AppRender.fetch.hello.this.is.a.test",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "56f25479131d0160",
    kind: "CLIENT",
    name: "fetching hello this is a test to see what happens get https://pokeapi.co/api/v2/pokemon/ditto",
    timestamp: 1725004322154000,
    duration: 168306,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      cached: "true",
      "http.method": "GET",
      "http.url": "https://pokeapi.co/api/v2/pokemon/ditto",
      "net.peer.name": "pokeapi.co",
      "next.span_name":
        "fetching hello this is a test to see what happens GET https://pokeapi.co/api/v2/pokemon/ditto",
      "next.span_type": "AppRender.fetch.hello.this.is.a.test",
      "node.env": "development",
      "operation.name": "next_js.AppRender.fetch.hello.this.is.a.test",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "9fa8e11ff5c8da91",
    kind: "CLIENT",
    name: "fetching hello this is a test to see what happens get https://pokeapi.co/api/v2/pokemon/ditto",
    timestamp: 1725004322153000,
    duration: 167870,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      cached: "true",
      "http.method": "GET",
      "http.url": "https://pokeapi.co/api/v2/pokemon/ditto",
      "net.peer.name": "pokeapi.co",
      "next.span_name":
        "fetching hello this is a test to see what happens GET https://pokeapi.co/api/v2/pokemon/ditto",
      "next.span_type": "AppRender.fetch.hello.this.is.a.test",
      "node.env": "development",
      "operation.name": "next_js.AppRender.fetch.hello.this.is.a.test",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "0d23af7915ad3d0f",
    id: "320f4a558a0efd5b",
    name: "render route (app) /",
    timestamp: 1725004322120000,
    duration: 209282,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.route": "/",
      "next.span_name": "render route (app) /",
      "next.span_type": "AppRender.getBodyResult",
      "node.env": "development",
      "operation.name": "next_js.AppRender.getBodyResult",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "db652399fd88a38e",
    id: "e292cb88211f8a7c",
    name: "rendering page",
    timestamp: 1725004322045000,
    duration: 286778,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.route": "/",
      "next.span_name": "rendering page",
      "next.span_type": "BaseServer.renderToResponse",
      "node.env": "development",
      "operation.name": "next_js.BaseServer.renderToResponse",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "e292cb88211f8a7c",
    id: "0d23af7915ad3d0f",
    name: "baseserver.rendertoresponsewithcomponents",
    timestamp: 1725004322115000,
    duration: 215820,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "BaseServer.renderToResponseWithComponents",
      "next.span_type": "BaseServer.renderToResponseWithComponents",
      "node.env": "development",
      "operation.name": "next_js.BaseServer.renderToResponseWithComponents",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "1091101f379b4b93",
    name: "start response",
    timestamp: 1725004322338000,
    duration: 84,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "start response",
      "next.span_type": "NextNodeServer.startResponse",
      "node.env": "development",
      "operation.name": "next_js.NextNodeServer.startResponse",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "320f4a558a0efd5b",
    id: "ba2e9b3abcd33662",
    name: "nextnodeserver.clientcomponentloading",
    timestamp: 1725004322147865,
    duration: 9993,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.clientComponentLoadCount": "5",
      "node.env": "development",
      "operation.name": "next_js",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "32b9b4b83d069519",
    id: "f65aee3be1f95dd7",
    name: "baseserver.render",
    timestamp: 1725004322044000,
    duration: 306793,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "BaseServer.render",
      "next.span_type": "BaseServer.render",
      "node.env": "development",
      "operation.name": "next_js.BaseServer.render",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "f65aee3be1f95dd7",
    id: "db652399fd88a38e",
    name: "baseserver.pipe",
    timestamp: 1725004322044000,
    duration: 305688,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "BaseServer.pipe",
      "next.span_type": "BaseServer.pipe",
      "node.env": "development",
      "operation.name": "next_js.BaseServer.pipe",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "edf4af49832f1a3f",
    id: "32b9b4b83d069519",
    kind: "SERVER",
    name: "get /",
    timestamp: 1725004319587000,
    duration: 2765249,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "http.method": "GET",
      "http.status_code": "200",
      "http.target": "/",
      "next.rsc": "false",
      "next.span_name": "GET /",
      "next.span_type": "BaseServer.handleRequest",
      "node.env": "development",
      "operation.name": "next_js.BaseServer.handleRequest",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    id: "a2f13357d6c2863c",
    name: "nextserver.getrequesthandler",
    timestamp: 1725004319585000,
    duration: 2767952,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "NextServer.getRequestHandler",
      "next.span_type": "NextServer.getRequestHandler",
      "node.env": "development",
      "operation.name": "next_js.NextServer.getRequestHandler",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
  {
    traceId: "a10c65aa60c2162e38362bf3710e0853",
    parentId: "a2f13357d6c2863c",
    id: "edf4af49832f1a3f",
    name: "nextserver.getserverrequesthandler",
    timestamp: 1725004319586000,
    duration: 2766438,
    localEndpoint: {
      serviceName: "next-cache-tracing",
    },
    tags: {
      "next.span_name": "NextServer.getServerRequestHandler",
      "next.span_type": "NextServer.getServerRequestHandler",
      "node.env": "development",
      "operation.name": "next_js.NextServer.getServerRequestHandler",
      "otel.library.name": "next.js",
      "otel.library.version": "0.0.1",
      "span.kind": "internal",
      "telemetry.sdk.language": "nodejs",
      "telemetry.sdk.name": "opentelemetry",
      "telemetry.sdk.version": "1.19.0",
      "vercel.runtime": "nodejs",
    },
  },
] as const;

export type Trace = typeof mockData;
